-- BUAT TABEL [TIPE_CUCI]

DROP TABLE [TIPE_CUCI]

CREATE TABLE [TIPE_CUCI]
(
	Id		INT NOT NULL PRIMARY KEY,
	Tipe	VARCHAR(100) NOT NULL
)

--TAMBAH TIPE CUCI
INSERT INTO TIPE_CUCI VALUES(1, 'Laundry') 
INSERT INTO TIPE_CUCI VALUES(2, 'Dry Clean') 


---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------


-- BUAT TABEL [BARANG]

DROP TABLE [BARANG]

CREATE TABLE [BARANG]
(
	Id				INT NOT NULL PRIMARY KEY IDENTITY, 
	Nama			VARCHAR(100) NOT NULL,
	Harga			INT NOT NULL,
	TipeCuciId		INT NOT NULL references TIPE_CUCI(Id)
)

--TAMBAH BARANG
INSERT INTO BARANG VALUES('Baby Seat/Car Seat', 50000, 1) 
INSERT INTO BARANG VALUES('Bantal/Guling', 30000 , 1) 
INSERT INTO BARANG VALUES('Bantal Kursi (60x60)', 30000 , 1) 
INSERT INTO BARANG VALUES('Bantal Kursi (45x45)', 25000 , 1) 
INSERT INTO BARANG VALUES('Bantal Kursi (30x30)', 14000 , 1) 
INSERT INTO BARANG VALUES('Baju Muslim (Atasan)', 14000 , 1) 
INSERT INTO BARANG VALUES('Baju Muslim (Atasan)', 17000 , 2) 
INSERT INTO BARANG VALUES('Baju Muslim (selutut)', 21000 , 1) 
INSERT INTO BARANG VALUES('Baju Muslim (selutut)', 24000 , 2) 
INSERT INTO BARANG VALUES('Baju Renang', 12000 , 1) 
INSERT INTO BARANG VALUES('Bedcover Jumbo (200x200)', 50000 , 1) 
INSERT INTO BARANG VALUES('Bedcover Double (180/160x200)', 40000 , 1) 
INSERT INTO BARANG VALUES('Bedcover Single (90/120x200', 35000 , 1) 
INSERT INTO BARANG VALUES('Blazer', 22000 , 1) 
INSERT INTO BARANG VALUES('Blazer', 27000 , 2) 
INSERT INTO BARANG VALUES('Blazer + Celana Pendek (1 set)', 36000 , 1) 
INSERT INTO BARANG VALUES('Blazer + Celana Pendek (1 set)', 44000 , 2) 
INSERT INTO BARANG VALUES('Blouse', 14000 , 1) 
INSERT INTO BARANG VALUES('Blouse', 17000 , 2) 
INSERT INTO BARANG VALUES('Blouse Tangan Panjang', 16000 , 1) 
INSERT INTO BARANG VALUES('Blouse Tangan Panjang', 19000 , 2) 
INSERT INTO BARANG VALUES('Blouse Batik', 20000 , 1) 
INSERT INTO BARANG VALUES('Blouse Batik', 23000 , 2) 
