-- BUAT TABEL COUNTER

CREATE TABLE [TBL_COUNTER]
(
	Kode_Counter	VARCHAR(10) NOT NULL PRIMARY KEY,
	Nama			VARCHAR(100) NOT NULL
)

--TAMBAH DATA COUNTER
INSERT INTO [TBL_COUNTER] VALUES('C001', 'Counter Setrasari') 
INSERT INTO [TBL_COUNTER] VALUES('C002', 'Counter Sarijadi') 