-- BUAT TABEL COUNTER
DROP TABLE [COUNTER]

CREATE TABLE [COUNTER]
(
	Kode_Counter	VARCHAR(10) NOT NULL PRIMARY KEY,
	Nama			VARCHAR(100) NOT NULL
)

--TAMBAH DATA COUNTER
INSERT INTO COUNTER VALUES('C001', 'Counter Setrasari') 
INSERT INTO COUNTER VALUES('C002', 'Counter Sarijadi') 