-- BUAT TABEL [TBL_PELANGGAN]

CREATE TABLE [TBL_PELANGGAN]
(
    Id INT NOT NULL PRIMARY KEY IDENTITY, 
    Nama NVARCHAR(50) NOT NULL, 
    Hp NVARCHAR(50) NOT NULL,
    NoKtp NVARCHAR(50) NOT NULL,
    Alamat NVARCHAR(50) NULL
)

--TAMBAH DATA COUNTER
INSERT INTO [TBL_PELANGGAN] VALUES('Pelanggan 1', '1', 'KTP1', 'Alamat 1') 
INSERT INTO [TBL_PELANGGAN] VALUES('Pelanggan 2', '2', 'KTP2', 'Alamat 2') 