-- BUAT TABEL [TBL_STAFF_COUNTER]

CREATE TABLE [TBL_STAFF_COUNTER]
(
	Kode			INT NOT NULL PRIMARY KEY IDENTITY, 
	Kode_Counter	VARCHAR(10) NOT NULL,
	Kode_Staff		NVARCHAR(128) NOT NULL,
	Jabatan			VARCHAR(20) NOT NULL
)

ALTER TABLE [TBL_STAFF_COUNTER] WITH CHECK ADD CONSTRAINT [STAFF_COUNTER_COUNTER_FK] FOREIGN KEY(Kode_Counter)
REFERENCES [TBL_COUNTER] (Kode_Counter)

ALTER TABLE [TBL_STAFF_COUNTER] WITH CHECK ADD CONSTRAINT [STAFF_COUNTER_STAFF_FK] FOREIGN KEY(Kode_Staff)
REFERENCES [AspNetUsers] (Id)

--TAMBAH DATA [TBL_STAFF_COUNTER]
INSERT INTO [TBL_STAFF_COUNTER] VALUES('C001', '68166985-f4d9-4d58-9299-595a3e103e97', 'Pengecekan') 
INSERT INTO [TBL_STAFF_COUNTER] VALUES('C002', 'a574886c-fd55-411d-b7f0-bfca1714cbcd', 'Staff') 