-- BUAT TABEL [TBL_TRANSAKSI_SATUAN]

CREATE TABLE [TBL_TRANSAKSI_SATUAN]
(
	Kode_Transaksi_Satuan			VARCHAR(20) NOT NULL PRIMARY KEY, 
	Kode_Counter					VARCHAR(10) NOT NULL,
	Kode_Staff						NVARCHAR(128) NOT NULL,
	Tanggal_Masuk					DATETIME NOT NULL,
	Tanggal_Keluar					DATETIME NULL,
	Total_Bayar						DECIMAL(10,2) NOT NULL,
	Total_Bayar_Revisi				DECIMAL(10,2) NOT NULL,
	Kode_Pelanggan					INT NOT NULL,
	Uang_Muka						DECIMAL(10,2) NOT NULL,
	Status_Transaksi				NVARCHAR(100) NOT NULL
)

ALTER TABLE [TBL_TRANSAKSI_SATUAN] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_COUNTER_FK] FOREIGN KEY(Kode_Counter)
REFERENCES [TBL_COUNTER] (Kode_Counter)

ALTER TABLE [TBL_TRANSAKSI_SATUAN] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_STAFF_FK] FOREIGN KEY(Kode_Staff)
REFERENCES [AspNetUsers] (Id)

ALTER TABLE [TBL_TRANSAKSI_SATUAN] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_PELANGGAN_FK] FOREIGN KEY(Kode_Pelanggan)
REFERENCES [TBL_PELANGGAN] (Id)