-- BUAT TABEL [TRANSAKSI_SATUAN_DETIL]
DROP TABLE [TRANSAKSI_SATUAN_DETIL]

CREATE TABLE [TRANSAKSI_SATUAN_DETIL]
(
	Kode_Transaksi_Satuan_Detil		INT NOT NULL PRIMARY KEY IDENTITY, 
	Kode_Transaksi_Satuan			VARCHAR(20) NOT NULL,
	Kode_Barang						INT NOT NULL,
	Jumlah							INT NOT NULL
)
GO

ALTER TABLE [TRANSAKSI_SATUAN_DETIL] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_DETIL_TRANSAKSI_SATUAN_FK] FOREIGN KEY(Kode_Transaksi_Satuan)
REFERENCES [TRANSAKSI_SATUAN] (Kode_Transaksi_Satuan)
GO

ALTER TABLE [TRANSAKSI_SATUAN_DETIL] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_DETIL_BARANG_FK] FOREIGN KEY(Kode_Barang)
REFERENCES [BARANG] (Id)
GO