-- BUAT TABEL [TBL_TRANSAKSI_SATUAN_DETIL]

CREATE TABLE [TBL_TRANSAKSI_SATUAN_DETIL]
(
	Kode_Transaksi_Satuan_Detil		INT NOT NULL PRIMARY KEY IDENTITY, 
	Kode_Transaksi_Satuan			VARCHAR(20) NOT NULL,
	Kode_Barang						INT NOT NULL,
	Jumlah							INT NOT NULL,
	Pengecek						NVARCHAR(128) NOT NULL,
	Revisi							INT NOT NULL
)

ALTER TABLE [TBL_TRANSAKSI_SATUAN_DETIL] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_DETIL_TRANSAKSI_SATUAN_FK] FOREIGN KEY(Kode_Transaksi_Satuan)
REFERENCES [TBL_TRANSAKSI_SATUAN] (Kode_Transaksi_Satuan)

ALTER TABLE [TBL_TRANSAKSI_SATUAN_DETIL] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_DETIL_BARANG_FK] FOREIGN KEY(Kode_Barang)
REFERENCES [TBL_BARANG] (Id)

ALTER TABLE [TBL_TRANSAKSI_SATUAN_DETIL] WITH CHECK ADD CONSTRAINT [TRANSAKSI_SATUAN_DETIL_PENGECEK_FK] FOREIGN KEY(Pengecek)
REFERENCES [AspNetUsers] (Id)