CREATE TABLE TIPE_CUCI
(
	Id		INT NOT NULL PRIMARY KEY,
	Tipe	VARCHAR(100) NOT NULL
)

CREATE TABLE BARANG
(
	Id		INT NOT NULL PRIMARY KEY IDENTITY, 
	Nama	VARCHAR(100) NOT NULL,
	Harga	INT NOT NULL,
	TipeCuciId INT NOT NULL references TIPE_CUCI(Id)
)

