CREATE TABLE BARANG
(
	ID		INT NOT NULL,
	NAMA	VARCHAR(100) NOT NULL,
	HARGA	INT NOT NULL,
	TIPE_CUCI_ID INT references TIPE_CUCI(ID)
	PRIMARY KEY (ID)
)

CREATE TABLE TIPE_CUCI
(
	ID		INT NOT NULL,
	TIPE	VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
)