
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JCleanLaundry
{

using System;
    using System.Collections.Generic;
    
public partial class StaffCounter
{

    public int Kode { get; set; }

    public string KodeCounter { get; set; }

    public string KodeStaff { get; set; }

    public string Jabatan { get; set; }



    public virtual Staff StaffFK { get; set; }

    public virtual Counter CounterFK { get; set; }

}

}
