
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JCleanLaundry
{

using System;
    using System.Collections.Generic;
    
public partial class TransaksiSatuan
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TransaksiSatuan()
    {

        this.TransaksiSatuanDetilFK = new HashSet<TransaksiSatuanDetil>();

    }


    public string Kode { get; set; }

    public string KodeCounter { get; set; }

    public string KodeStaff { get; set; }

    public System.DateTime TanggalMasuk { get; set; }

    public Nullable<System.DateTime> TanggalKeluar { get; set; }

    public decimal TotalBayar { get; set; }

    public decimal TotalBayarRevisi { get; set; }

    public int KodePelanggan { get; set; }

    public decimal UangMuka { get; set; }

    public string StatusTransaksi { get; set; }



    public virtual Staff StaffFK { get; set; }

    public virtual Counter CounterFK { get; set; }

    public virtual Pelanggan PelangganFK { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransaksiSatuanDetil> TransaksiSatuanDetilFK { get; set; }

}

}
